# This generates a login token for the "jenkins" service account
# GitHub Actions uses this token to authenticate with Kubernetes
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: mysecretname
  namespace: webapps
  annotations:
    kubernetes.io/service-account.name: github-actions
